### ISSUE TITLE
Conflicting datatype for hal_network_params_t structure

### ISSUE THREAD

**Issue by SanthoshGujulvajagadeesh** [rdkcentral/rdkb-halif-platform#23]
Build error:
```
error: conflicting types for 'protocol_t'
18:53:11  |  1460 | } protocol_t;
18:53:11  |       |   ^~~~~~~~~~
```
Reason for change:
Renaming enum datatype from `protocol_t` to `net_proto_t` to resolve the conflict.

**Comment by GoutamD2905** [comment]
Changes are merged into the main with the new Release tag 1.3.2
