### ISSUE TITLE
gh1 - updating platform_hal file for Unify Wan Manager

### ISSUE THREAD

**Issue by GoutamD2905** [rdkcentral/rdkb-halif-platform#4]
updating the platform_hal file for Unify Wan Manager happened on RDKB-48051 ticket

**Comment by Ulrond** [comment]
Extended the DHCP defines to support extended options.

**Comment by GoutamD2905** [comment]
Addressed this issue on https://github.com/rdkcentral/rdkb-halif-platform/pull/6
